### ISSUE TITLE
easier set tempo parameter

### ISSUE THREAD

**Issue by lplume** [grimmdude/MidiWriterJS#10]
It would be good to have the set tempo parameter as beats/minute instead of the plain midi format

**Comment by lplume** [comment]
reopen, there is a bug on [setTempo function](https://github.com/grimmdude/MidiWriterJS/blob/master/src/midi-writer-js.js#L85), the tempo should be cast to integer before passing it to numberToBytes (im gonna do this soon, sorry :-\)

**Comment by grimmdude** [comment]
Ah ok, thanks for catching.

-G
