### ISSUE TITLE
Midi arrangement help

### ISSUE THREAD

**Issue by gilesbutler** [grimmdude/MidiWriterJS#101]
Hi there,

Awesome library and thanks so much for you work.

I'm trying to create a structure like the one below but getting stuck and not sure if it's possible?

I'd like to create either empty midi blocks or it's ok if they have one long note in for the length of the block.
And the ability to add space before and after the blocks of midi.

Is this possible?

Thanks

<img width="459" alt="CleanShot 2022-11-07 at 20 01 26@2x" src="https://user-images.githubusercontent.com/790734/200269747-0f3cb1dd-1b97-4811-a6dd-233d1992f633.png">

**Comment by grimmdude** [comment]
Hi @gilesbutler,

I'm not sure if I understand your question fully, but each midi file created by this library will create one continuous block of MIDI per track.

**Comment by grimmdude** [comment]
Closing this for now @gilesbutler, but let me know if I can help any further.

**Comment by gilesbutler** [comment]
Thanks for the response @grimmdude 👍 After digging a bit further I think it’s actually a limitation of midi itself, I don’t think the midi spec has the notion of clips. I arrived at the same outcome as your comment that you have to have one continuous block of midi per track. I assume it’s the DAWs that program in support for “midi clips”.
