### ISSUE TITLE
How to create a midi file

### ISSUE THREAD

**Issue by jepcolombia** [grimmdude/MidiWriterJS#115]
I would appreciate an example on how to write a midi file or do we have to use an extra library?

**Comment by dirkk0** [comment]
It is pretty straightforward to write out the file, thankfully.

You basically do this:

```
const buffer = new Buffer.from(w.buildFile());
fs.writeFileSync('song.mid', buffer, function (err) {
    if (err) throw err;
});
```

with `w` being a `new MidiWriter( ... )`.

I can provide a full example if needed.

**Comment by jepcolombia** [comment]
Thank you very much . If you can provide full example I would appreciate it
very very much
Best regards
Jairo

**Comment by jepcolombia** [comment]
Trying to use the example provided bu a syntax error appears Undefined ¨Buffer ¨.  do I need to add something else?
Thanks in advance

**Comment by grimmdude** [comment]
Thanks for your help @lplume & @dirkk0 🙏
