### ISSUE TITLE
New Tag

### ISSUE THREAD

**Issue by FredericoGauz** [grimmdude/MidiWriterJS#118]
Hi, thanks for the amazing repo! Would it be possible to create a new tag with the recent typescript changes?

**Comment by grimmdude** [comment]
Hey @FredericoGauz, I just released [3.0.0](https://github.com/grimmdude/MidiWriterJS/releases/tag/v3.0.0).  Hopefully I didn't break anything, lmk though 😃

**Comment by FredericoGauz** [comment]
Hi Garett,

Thank you for letting me know. Have a good weekend!
