### ISSUE TITLE
Indian music in western notation

### ISSUE THREAD

**Issue by lplume** [grimmdude/MidiWriterJS#13]
#12 #4 
@shivrajsa
Please refer to this issue.
First of all I'm sorry if I'm gonna makes some mistakes, consider I do not know about Indian music a lot.

Think in quarter, consider the teentaal it's a 16 beats cycle, wrapped at 4 (4/4/4/4), so my suggestion is to start a time signature of 16/4 (the whola cycle). This mean that everyone of each
`dhaa dhin dhin dhaa/ dhaa dhin dhin dhaa/ dhaa tin tin taa/ taa dhin dhin dhaa` is a quarter note.

Suppose the nth beat should contain two notes of melody (in Bhatkhande notation system something like: SaNi) **so every notes of that beat** would be the half of a quarter (in western notation it will be the _eighth note_). If you need to dived one single beat in an odd number of notes (3,5,7) so you will use triplet, quintet and so on.
Every single beat in your cycle counts of one quarter, and you can fill it with an amount of notes which the total duration equals to one quarter.

Think of the rupak: it is a 7 beats cylce made of 3 + 2 + 2
`ti ti naa / dhi naa / dhi naa`, so your signature will be 7/4 and group them as three two and two.

Here follow the MidiWriterJS code to generate 

> bandish in Raag Kedar, set to the Teentaal rhythm cycle, sung or played at a lively (drut) tempo

please refer to this link http://raag-hindustani.com/Notation.html

**THE FOLLOWING WILL NOT WORK** (there are some works to do on MidiWriterJS to supports
more western music notation), but it still a valid example of how you can do it.
Also note that, because of the above sentence, this is only the 1st refrain.

```javascript
    var tracks = [];

    tracks[0] = new MidiWriter.Track();
    // Western equivalent for Standard Teental (16 beat cyle, 4 sections of 4 beats)
    // In western 16/4 means that ONE single beat is the sum of 16 quarter notes
    // which fits perfect a standard Teental
    tracks[0].setTimeSignature(16, 4);

    // Equivalent for Drut Laya
    tracks[0].setTempo(160);

    var notes;

    // melody
    tracks[1] = new MidiWriter.Track();
    notes = new MidiWriter.NoteEvent({wait:'1.', pitch:['C4', 'D4', 'C4', 'G4', 'G4', 'G4', 'F#4', 'G4'], duration: '4', sequential: true});
    tracks[1].addEvent(notes);

    notes = new MidiWriter.NoteEvent({pitch:['A4', 'A#4', 'A4', 'G4'], duration: '4', sequential: true});
    tracks[1].addEvent(notes);

    notes = new MidiWriter.NoteEvent({pitch:['F#4', 'G4', 'A4', 'G4'], duration: '8', sequential: true});
    tracks[1].addEvent(notes);

    notes = new MidiWriter.NoteEvent({pitch:['F4', 'F4'], duration: '2', sequential: true});
    tracks[1].addEvent(notes);

    notes = new MidiWriter.NoteEvent({pitch:['G4', 'G4'], duration: '4', sequential: true});
    tracks[1].addEvent(notes);

    notes = new MidiWriter.NoteEvent({pitch:['C5'], duration: '2', sequential: true});
    tracks[1].addEvent(notes);

    notes = new MidiWriter.NoteEvent({pitch:['A4', 'G4'], duration: '4', sequential: true});
    tracks[1].addEvent(notes);

    notes = new MidiWriter.NoteEvent({pitch:['F4'], duration: '2', sequential: true});
    tracks[1].addEvent(notes);

    notes = new MidiWriter.NoteEvent({pitch:['A4', 'G4'], duration: '4', sequential: true});
    tracks[1].addEvent(notes);

    notes = new MidiWriter.NoteEvent({pitch:['F4', 'D4'], duration: '4', sequential: true});
    tracks[1].addEvent(notes);

    notes = new MidiWriter.NoteEvent({pitch:['C4'], duration: '2', sequential: true});
    tracks[1].addEvent(notes);
```

**Comment by shivrajsa** [comment]
Thank you @lplume for detail answer, you have done really good study of Indian classical music. :-).
I am still finding difficult to understand how time signature works, especially denominator. As per my understanding 

- When we say 16/4, it means 16 beats in one bar (I dont know what is bar, but it seems it is division of group of beats). 
- When we say 7/4, it means 7 beats in one bar, in this case what is significance of denominator 4? when we already know we want to divide bar in 7 equal parts ?

I am wondering how can I write a below case?
assume there are 16  bars (Teean taal 16 divisions (beats)) in my composition. in each bar I want to put number of notes  = bar number i.e. 1st bar 1 note, 2nd bar 2 notes, 3rd bar 3 beats . . . so on. . .16th bar 16 beats. 

In a composition of Indian classical music it is possible to have odd/even number of notes in any beat/bar/division.

**Comment by lplume** [comment]
@shivrajsa thank you =) it took me hours of rest :joy:
There are two problmes as far as i can understand

1. First of all consider Western and Indian music have different roots, some concept could be shared, but keep in mind they are different 
2. Digital notation of Indian music is still young and fresh (as far as I know notation in general)

**Time signature**
In western music bars are single chunks of a composition, like the grouping in Bhatkhande´s notation and alike. That´s why I think notating Indian music the time signature should be the cycle itself. In taal equally grouped (teeen taal as example) you could use a time signature of 4/4 and you know that every 4 bars the cyles end. But take taal not equally grouped (rupak) 3 + 2 + 2, the time signature will change every time the cycle begin and end: one bar 3/4, two bars 2/4. The signature mean: the numerator is the number of notes of duration at the numerator per bar. 3/4 means that a bar is made up of 3 notes of one quarter. In one bar you can write up to the sum of three quarter.
Time signature could happen, but changing it too often is not comfortable to read. That´s why i think the time signature should be the cycle itself.

[note value chart (wikipedia)](https://en.wikipedia.org/wiki/Note_value): here notation for western music note values
[note tuplet (wikipedia)](https://en.wikipedia.org/wiki/Tuplet): here notation for western music note tuplet (odd groups of note); if you divided a quarter note in two equal notes (like putting two notes in Indian composition in one beat) that notes are two eighth. If you split a quarter note in three equals so you have a triplet and so one.

So, if your composistion will be bar number = notes
16/4
1. one quarter
2. two eighth
3. one triplet
4. four sixteenth
5. one quintuple
6. one sextuplet
7. one septuplet
8. eight thirty-second
etc etc, but it´s pretty unusual notating like that :confused: well, if you only need it for a MIDI playback so no problems! Anyway at the moment MidiWriterJS do not support all that timeing.

**Comment by grimmdude** [comment]
Thanks @lplume, closing this one out
