### ISSUE TITLE
Develop branch

### ISSUE THREAD

**Issue by lplume** [grimmdude/MidiWriterJS#15]
Hi Garrett,

Would be a good idea to have a develop (or more, see git flow) branch(es), so the master branch will be always clean and stable.

-Mauro

**Comment by grimmdude** [comment]
Hi Mauro,

I'm actually considering the master branch as the dev branch currently.  Let's use the releases as the tested stable versions; https://github.com/grimmdude/MidiWriterJS/releases  I will create a new release with our latest changes.

I'll make a note in the README so people viewing the repo understand this.

-Garrett

**Comment by lplume** [comment]
Nice, no matter how =) just tell us how to help you and this library! Great work Garrett!

-Mauro
