### ISSUE TITLE
Add support for exporting MIDI from VexFlow

### ISSUE THREAD

**Issue by grimmdude** [grimmdude/MidiWriterJS#16]
Would be cool, and fairly trivial, to support MIDI export from [VexFlow](https://github.com/0xfe/vexflow)

**Comment by msj121** [comment]
Is there a way to show on the VexFlow object the note or at least the section being played? This would  be a pretty neat way to tie into the visualization of vexflow and your export.

**Comment by grimmdude** [comment]
Hi @msj121 

I'm not sure I understand your question.  This library is for generating MIDI, but not playing it.  The VexFlow object does contain note information, this is what MIDIWriterJS uses to generate the MIDI.

-Garrett

**Comment by msj121** [comment]
@grimmdude Oh I see. Thanks. If I did decide to play it side by side with the notes in VexFlow, do you have any advice how I might be able to tie the midi music to the sheet music? Do I only have timing to work with, from VexFlow and assume the Midi lines up?

Thanks.

**Comment by grimmdude** [comment]
Hi @msj121 ,

You would need to implement some type of sequencer then tie in the note events from that into VexFlow.  I think [Midi.js](https://github.com/mudcube/MIDI.js/) might have support for that, I'm not sure though.

-Garrett
