### ISSUE TITLE
github pages broken

### ISSUE THREAD

**Issue by joernroeder** [grimmdude/MidiWriterJS#2]
hey,
i've tried to check out the demo but got a bunch of `Blocked loading mixed activce content` Errors for your css and js files. i looked in your config file as well but couldn't find a `github.url` variable there. Changing all links to `https://` should fix it.

https://developer.mozilla.org/en-US/docs/Security/Mixed_content#Warnings_in_Web_Console

**Comment by grimmdude** [comment]
Hi There,

Thanks for you message.  Are you using a browser plugin which forces https?  The demo should be fine without it.

-Garrett

**Comment by grimmdude** [comment]
I went ahead and hard coded those links to use https urls.  Thanks,

-Garrett

**Comment by joernroeder** [comment]
Jup, I'm using https://www.eff.org/https-everywhere
