### ISSUE TITLE
how can i change the music instruments?

### ISSUE THREAD

**Issue by Jandou6** [grimmdude/MidiWriterJS#23]
are there any doc? because i found that your other project (MidiPlayer) , mentioned the sound_font.

so,I think that it may be can choose the other instrument not only the piano sound.

**Comment by grimmdude** [comment]
Hi @Jandou6,

You can change the instrument like this:
```js
// Define an instrument (optional):
track.addEvent(new MidiWriter.ProgramChangeEvent({instrument : 1}));
```

Here's a table describing each program: https://www.midi.org/specifications/item/gm-level-1-sound-set

-Garrett

**Comment by Jandou6** [comment]
@grimmdude  Oh ~ is great !! Thanks. the MidiWriterJs is Great.I love it

**Comment by grimmdude** [comment]
Cool thanks!
