### ISSUE TITLE
Time Signature Denominator 8

### ISSUE THREAD

**Issue by Jorbf13** [grimmdude/MidiWriterJS#24]
Hello,

I seem to be getting some problems downloading files with a time signature denominator of 8. With Logic/Garageband, the the DAW doesn't even really recognize the file, but it imports the tempo and the time signature with a denominator of 4. Ableton imports it with the denominator 4 and an added note at C0 with a duration equal to the length of the file.
All DAWs I mentioned work just fine for denominators of 4 and 16.

Does this seem like it could be an error on your end of the code?

Thanks a lot!

**Comment by grimmdude** [comment]
Hi @Jorbf13 ,

Thanks for reporting, sounds like it is probably an issue in this library.   Let me do some tests and hopefully get a fix out shortly.

-Garrett

**Comment by Jorbf13** [comment]
Great, thanks being so responsive!

I'm also getting tempo imports such as 163.9998 instead of 164. Some DAWs round it up (Ableton), but Logic imports the whole float, and Garageband rounds it down. If you'd like I can make a separate issue for this.

**Comment by lplume** [comment]
Well.. shame on me.. it's actually a terrible fault of mine, check this

https://github.com/grimmdude/MidiWriterJS/blame/master/src/track.js#L69

**Comment by grimmdude** [comment]
Thanks @lplume , I'll take a look at that time signature issue.

@Jorbf13 could you open a new issue for the tempo rounding problem you're seeing?

-Garrett

**Comment by lplume** [comment]
@grimmdude great =D ty; the time signature is that if the denominator is more than 4, then it is expressed as pow of 2, i ew... just square root it ^^' that's why 4 and 16 are fine but not.. 8

**Comment by Jorbf13** [comment]
Yay, yes, thanks @grimmdude @lplume ! I tested using log2 instead of sqrt in my local files and it seems to work fine!

**Comment by grimmdude** [comment]
Hi @Jorbf13,

Yep good call that's the ticket.  Just pushed this change and published 1.4.4 to npm.  Thanks for reporting and solving!

-Garrett
