### ISSUE TITLE
how can i set NoteEvent.wait for  longer?

### ISSUE THREAD

**Issue by Jandou6** [grimmdude/MidiWriterJS#26]
you write the Description for wait time:
1 : whole
2 : half
d2 : dotted half
4 : quarter
d4 : dotted quarter
8 : eighth
8t : eighth triplet
d8 : dotted eighth
16 : sixteenth
Tn : where n is an explicit number of ticks

But if I want to wait for longer,how can i do for this.

such i want to wait 8s. And I don't know what the mean of 'Tn(where n is an explicit number of ticks)'

**Comment by grimmdude** [comment]
Hi @Jandou6 

I've just pushed a change which allows you to use an array of durations where the sum will be used in the note event.  Not sure if that's helpful  to you or not, but it's nice to have.

To explicitly wait for 8 seconds you could use the `Tn` option.  By default this library assumes there are 128 ticks per beat, so the formula would work out how many ticks there are per second is:

` bpm/60 * 128 = ticksPerSecond`

So to work out how many ticks there are in 8 seconds it would be:

`bpm/60 * 128 * 8`

I suppose I could add a 'seconds' option to make this easier...

-Garrett

**Comment by Jandou6** [comment]
thank you very much!
