### ISSUE TITLE
wrong midi pitch

### ISSUE THREAD

**Issue by LagodViads** [grimmdude/MidiWriterJS#27]
track.addEvent(new MidiWriter.NoteEvent({
    pitch : ['C4','B#4'],
    duration : '4'
}));
writes as C4,C4 ; should be C4 C5

I suggest using tonal.note.midi given your claim to support tonal.note output.

**Comment by grimmdude** [comment]
Hi @LagodViads 

Thanks for the suggestion.  I've updated this to use [tonal-midi](https://github.com/danigb/tonal/tree/master/packages/midi) to lookup MIDI numbers from note names so this issue should now be fixed.

-Garrett

**Comment by LagodViads** [comment]
Perfect!
