### ISSUE TITLE
[ DISCUSSION ] About NoteEvent

### ISSUE THREAD

**Issue by lplume** [grimmdude/MidiWriterJS#3]
I am very interested in this project, would like to know more about the note event, especially the sequential option. I can get the point of wrapping note on/off in one note event, but the sequential is still a very ¨special uses case¨. There should be more wrappers of note event itself (chords, tuple, sequential), it should result in a more clear API. Or the pitch array could be an array of objects (note/duration etc)..

Not sure if it makes any sense (maybe i misunderstood the scope of the project), but, once you call an addEvent, there are no way to come back except re-executing the whole source.

What about keeping track of the chunks (related to its MidiWriterJS representation) so it can be possible to edit it?

Thanks

**Comment by grimmdude** [comment]
Thanks for the message.  I found the `sequential` option quite useful when writing out the Chopin Prelude example.  It's much less verbose for when you need to write sequential notes which are the same duration.  More wrappers could be added to the note on/off events though as you suggest, though couldn't you write chords/tuples with the existing syntax?  I'm open to suggestions.

Right, currently there is no way to traverse around the MIDI events once they have been committed with `addEvent()`.  This is something that could be added.  How would you access the added events, by index?

-Garrett

**Comment by lplume** [comment]
Hi Garrett,

Thanks for your answer!

Let me first state I really don't know midi specifications. As far as I know you model the add note event as you can write chords (sequential: false) and (at least) the 8th triple (8t). I would like to dig into midi specification and how other software deal with it. I just was wondering how low or high level would fit the library itself: if you add addChords([notes], {duration etc}) would be a shortcut for sequential:false; it is a point of view: a function against an option.

Since the event is concat to the data converted to midi, an array of event with it's offset in the data could solve the "issue"?

Again, give me sometime to better understand midi format and I will give you more feedback! Really would love to collaborate!!

This library is supereffective :D !!

**Comment by lplume** [comment]
One way to ¨traverse¨ around the MIDI events should be to store every single event (an array of objects) and compute the conversion to MIDI on every addEvent for events from scratch. What you think of this solution?

-Mauro

**Comment by grimmdude** [comment]
Hi Mauro,

To clarify, your idea is to rebuild the entire MIDI data every time an event is added correct?

I like the idea of building an event array so it's traversable, but it probably makes more sense to build the actual data from that array once the `Writer` object is instantiated.  Otherwise rebuilding the MIDI data on each `addEvent` for large MIDI files it could become too taxing.  I think I have an idea on how this could be implemented, I'll give it a shot.

With that said, what is the use case traversing the event tree?  It's not clear to me why this is needed.

**Comment by lplume** [comment]
I agree your point on building MIDI data on ¨request¨.
One use case could be to integrate the library into larger application, an example could be a piano roll
