### ISSUE TITLE
Grace Notes

### ISSUE THREAD

**Issue by gciluffo** [grimmdude/MidiWriterJS#32]
@grimmdude 

I am interested in adding some more functionality to the vexflow part, and was wondering if I could get some guidance on MidiWriter to handle grace notes?

Since a grace note comes right before its target note, what would be the best way to create a NoteEvent for that grace note. I was thinking of adding the grace note to a separate track from the target note? Something like:

Adding a 8th note grace note to a quarter note
```
var gracenote = new MidiWriter.NoteEvent({wait: '8', pitch:['E5'], duration: '8'});
tracks[2].addEvent(gracenote);
var targetnote = new MidiWriter.NoteEvent({pitch:['E5'], duration: '4'});
tracks[1].addEvent(targetnote);
```
Although I think that would just play the gracenote after the quarter an 8th of a beat later? Any thoughts on best way to do this?

**Comment by grimmdude** [comment]
Hi @gciluffo,

Interesting question.  Currently I would say this isn't really supported, although I suppose you could manually prefix a note with a 16th note (64th would probably be ideal, support should be added for that as well):

```js
var track = new MidiWriter.Track();
var notes = [];
notes.push(new MidiWriter.NoteEvent({pitch:['Eb5'], duration: '16'}));
notes.push(new MidiWriter.NoteEvent({pitch:['E5'], duration: '4'}));

track.addEvent(notes);
```

Of course you would need to adjust any previous note's duration to account for this so everything stays in time.

Ideally, I think a new `NoteEvent` property should be added which handles this for you.  Something like:

```js
var note = new MidiWriter.NoteEvent({pitch:['E5'], duration: '4', grace: ['Eb5']});
```

Where `grace` could be an array of pitches which quickly prefix the target note while maintaining target duration.  What do you think?  I will add this to my list.

-Garrett

**Comment by gciluffo** [comment]
@grimmdude 

Im messing around with it a little bit now with 64th notes and seems that a 64th note being the grace note isnt fast enough. I believe a gracenote should be executed with the target note at the exact same time, but just a smidge behind. My music theory is a little rusty but I think the space between a grace note and its target note would not be dependent on tempo. Adding a 64th note would create a larger space between the gracenote and target note as tempo decreases and create a smaller space as tempo increases.

Playing around with the MAURO GIULIANI example you wrote I noticed that some notes were graced when playing them through a midi player. The target and grace notes were both on seperate tracks, im not sure if this was intentional or not?

**Comment by grimmdude** [comment]
I agree, using metric notes as grace notes won't really work very well.  I will try to get that `grace` property added to the `NoteEvent` object shortly.

-Garrett

**Comment by grimmdude** [comment]
Hi @gciluffo,

I've added an implementation of the `grace` property to the master branch.  It's used as I suggested  above:

```js
var note = new MidiWriter.NoteEvent({pitch:['E5'], duration: '4', grace: ['Eb5']});
```

Give that a shot and let me know how that works for you.  Currently grace notes default to a duration of 10 ticks.  That might need to be adjusted though based on tempo.

-Garrett

**Comment by gciluffo** [comment]
@grimmdude 

Hey thanks for getting to this. I tested this a little bit using your Midi Player Js library. The main issue is that Im still hearing that the space between the target not and grace is a little too large. Would it be easy to shorten that distance?

**Comment by grimmdude** [comment]
Hi @gciluffo,

Yea I see what you mean.  I just pushed a change to reduce the grace note duration to a single tick; it doesn't get any shorter than that unless we change the note division.  Here's what I'm testing with, sounds ok to me though it doesn't look pretty in notation:

```js
track.addEvent([
	new MidiWriter.NoteEvent({pitch: ['E4'], duration: '4', grace:['Eb4']}),
	new MidiWriter.NoteEvent({pitch: ['F#4'], duration: '4', grace:['F4']}),
	new MidiWriter.NoteEvent({pitch: ['G#4'], duration: '4', grace:['G4']}),
	new MidiWriter.NoteEvent({pitch: ['A4'], duration: '4', grace:['G#4']}),
	new MidiWriter.NoteEvent({pitch: ['B4'], duration: '4', grace:['A#4']}),
	new MidiWriter.NoteEvent({pitch: ['C#5'], duration: '4', grace:['C5']}),
	new MidiWriter.NoteEvent({pitch: ['D#5'], duration: '4', grace:['D5']}),
	new MidiWriter.NoteEvent({pitch: ['E5'], duration: '4', grace:['D#5']})
]);
```

What do you think?

-Garrett

**Comment by gciluffo** [comment]
@grimmdude 

Sounds good to me. Are you adding grace notes to all those notes to account for offset? So everything stays in time.

**Comment by grimmdude** [comment]
Hi @gciluffo,

I'm just adding grace notes to all those notes above for testing.  The way it's setup, when a single tick duration grace note is added to a note event that single tick will be subtracted from the note event's duration so it should keep everything in time.

It sounds fine, but as I mentioned when you look at the notation it tends to look kinda funny (in MuseScore 2 anyway)  because of the tiny note duration.

-Garrett
