### ISSUE TITLE
Vexflow, note doublings

### ISSUE THREAD

**Issue by gciluffo** [grimmdude/MidiWriterJS#33]
@grimmdude 

Me again, was wondering whats the best way to handle doubling a note? Say for example I have a 16th note that needs to get doubled into two 32nd notes. Currently MidiWriter does not support 32nd notes as far as I can see? What would be the best way to do this?

**Comment by grimmdude** [comment]
Hi @gciluffo,

Thanks for the note, I've just pushed an update which includes 32nd and 64th notes.

-Garrett
