### ISSUE TITLE
Support quarter note triplets and 16th note triplets?

### ISSUE THREAD

**Issue by scraggo** [grimmdude/MidiWriterJS#34]
Would it be difficult to add support for:
- '4t' as quarter note triplet (1.3333333)
- '16t' as 16th note triplet (.133333333)

If not, I could add those to the src file and wherever else determines it

If so, I can specify with ticks, correct?

**Comment by gciluffo** [comment]
@scraggo 

Ya pretty much, itd be as easy as that. Look at <a href="https://github.com/grimmdude/MidiWriterJS/commit/e5e69cd9d62ae03db8fb52fde0b17584a8a430dd">this</a> commit
