### ISSUE TITLE
ReferenceError: fs is not defined

### ISSUE THREAD

**Issue by LogIN-** [grimmdude/MidiWriterJS#35]
I am getting following error message when trying to use saveMIDI function.
I think that fs node module is not included properly in the library.

```
/xyz/node_modules/midi-writer-js/build/index.js:1005
            fs.writeFile(filename + '.mid', buffer, function (err) {
            ^

ReferenceError: fs is not defined
    at Writer.saveMIDI (/xyz/node_modules/midi-writer-js/build/index.js:1005:4)
    at Object.<anonymous> (/xyz/example.js:27:7)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
```

**Comment by grimmdude** [comment]
Hi @LogIN- 

`Writer.saveMIDI()` is only available in a NodeJS environment.  I assume you're trying to save file from a browser?  If so you can try `Writer.dataUri()`

-Garrett

**Comment by LogIN-** [comment]
Hi @grimmdude 
Thanks for a response and sorry for bad bug report.

Actually I was trying to use the module in nodejs via command line. I tried to quickly browse MidiWriterJS code and I could not find anywhere that fs module is included. 

I am not sure, maybe if this is working for you, than something in my environment is probably messed up.

**Comment by grimmdude** [comment]
Hi @LogIN- 

Ah ok, yes you're right; it doesn't look like `fs` is necessarily available in that function.  I've been thinking about removing that function actually.  I'd recommend just grabbing the buffer from the `Writer` object and saving the file in your own logic.  Similar to:

```js
var fs = require('fs');
var buffer = new Buffer(writer.buildFile());
fs.writeFile(filename + '.mid', buffer, function (err) {
    if(err) return console.log(err);
});
```
-Garrett
