### ISSUE TITLE
how to play through stem?

### ISSUE THREAD

**Issue by lingxinc** [grimmdude/MidiWriterJS#38]
how to play through stem?
![35836544-c45b9724-0b1b-11e8-8e0b-ba7db8342036](https://user-images.githubusercontent.com/26563603/35902195-45e978ca-0c15-11e8-834b-bbffeeff18c1.jpg)

**Comment by grimmdude** [comment]
Hi @lingxinc,

Can you clarify your question a bit?

-Garrett

**Comment by lingxinc** [comment]
I'm sorry, I am working hard on my Englishl!
I want to ask how to add a note with vibrato.

**Comment by grimmdude** [comment]
Hi @lingxinc,

You can use a `ControllerChangeEvent` to apply modulation to your track, which could be used as vibrato.  The `controllerNumber` for modulation is `1` and the range for the `controllerValue` is `0` - `127`.

```js
const track = new MidiWriter.Track();

track.addEvent([
    new MidiWriter.ControllerChangeEvent({controllerNumber: 1, controllerValue: 127}),
    new MidiWriter.NoteEvent({pitch: 'C4', duration: '2'}),
]);

```
