### ISSUE TITLE
Is it possible to give duration in miliseconds?

### ISSUE THREAD

**Issue by shivrajsa** [grimmdude/MidiWriterJS#4]
This library seems very interesting. 
Is it possible to give duration in milliseconds, or full control over duration instead of fix values.

**Comment by grimmdude** [comment]
Hi There,

Assigning millisecond durations is not currently support, though it's something that can be added.  I'm not sure how tempo would be accounted for though, I suppose it would have to be a fixed value in this case?

-Garrett

**Comment by shivrajsa** [comment]
I have Indian classical music project using MIDI.js where user can have any number of notes in one beat & user can give tempo as a number for example 222 BPM, here is an example [http://vishwamohini.com/music/demo-notations.php]
so while generating MIDI file I will need duration in milliseconds, I already have MIDI file generation feature, but base 64 string generated is not giving correct output with MIDI player of MIDI.js so I want to try your library for generating base 64 string which will be used as input for MIDI.js player. It would be great if you add support for duration in miliseconds. I have used [https://github.com/sergi/jsmidi] library to generate MIDI file

**Comment by lplume** [comment]
Well, i think it could be possibile, work should be done on how every <delta_time> is computed. Basically the timing in MIDI is based on ¨ticks¨ per quarter note. That´s why timing in music is usually ¨fixed symbols¨ (like quarter, half and so on) and not seconds. It does not matter how seconds last a note, a note is a quarter, half, eighth... The real duration is based on the time signature (well while playing irl is a matter of the executor and expression).

@shivrajsa may I ask you why a user should give any number of notes in one (single big) beat? Do you know of any other MIDI usage like what you are asking?

@grimmdude still digging into MIDI format, but: in the header chunk; the last 16 bit defines the division

> MSB 0; 0-14 number of delta-time units in each a quarter-note {ticks per beat}.
> MSB 1; 0-7 number of delta-time units per SMTPE frame; 8-14 form a negative number, representing the number of SMTPE frames per second {don´t know about SMTPE}

While in the track chunk every event is preceded by the delta_time
>  the number of 'ticks' from the previous event

The default tempo is 120 bpm (and can be changed through a meta event)
> In the case where the value of <division> (in the header chunk) defines delta-time units in 'ticks per quarter note' (MSbit=0), a change in tempo means a change in the length of a unit of delta-time.
> In the case where <division> MSbit=1, and the 'ticks' are defined in absolute terms (ticks/frame and frames/second), it is not clear from the specification what effect a new tempo should have.

It can be done (especially {only?} if the division´s is setted as ticks per beat), but not pretty sure if it´s a good idea, i think timing in *seconds is useful to sync differents devices and not for ¨music compositions¨ itself

-Mauro

**Comment by shivrajsa** [comment]
@lplume thank you for your answer.
Actually I am not expert in MIDI & even I dont know how time signatures are used in western music.


Lets take this use case
1. Assume one beat of one second.
2. I want to play 7 notes in one beat (one second). It means one second is devided into 7 equal parts
One beat devided in 7 parts
Devisions  = 1 | 2 | 3 | 4 | 5 | 6 | 7
Notes        = 1 | 1 | 1 | 1 | 1 | 1 | 1
3. I also want to play two/four notes in any part of devided beat, please refer below 2nd & 6th part of devided beat. 
One beat devided in 7 parts
1  |  2   |  3  |  4  |  5  |    6    |  7
1  | 12  |  1  |  1  |  1  | 1234 |  1

In MIDI.js, which is library I have used in my project, we can handle such use cases because it takes 'delay' as number.
But I am wondering how to handle such use cases in this library when time signature is string.
Instead of requesting support for milliseconds I should have asked for duration as number than string in my question

Use case I shared above is very common in Indian classical music, also 7 can be replaced by 4,5,6,7,8,9,10,11 . . .
Please guide.

**Comment by lplume** [comment]
@shivrajsa  now I get it, give me some more time to better understand indian music notation and structure and i will be back again. I will be glad (if you mind) to give you back some resource about western music as well!

**Comment by grimmdude** [comment]
Hi @shivrajsa,

Assuming the song is 7 beats per second for the whole time I think you can accomplish this with a little math using the currently available note divisions.  I believe 7 beats per second would come out to 420bpm.  Once that tempo is set each beat is considered a quarter note, and the division you're looking for can be accomplished by using 8th and 16th notes.  This was quick math in my head so I could be wrong, but I think that should work.

-Garrett

**Comment by shivrajsa** [comment]
@lplume do share western music resources, it will be useful.

**Comment by lplume** [comment]
this could be closed in favor of #13
