### ISSUE TITLE
Error MidiWriter is not defined

### ISSUE THREAD

**Issue by fornof** [grimmdude/MidiWriterJS#40]
So, I have a "Uncaught ReferenceError: MidiWriter is not defined" , even though I imported on the front end. 
There is a folder in node_modules for "Browser" index.min.js , I was hoping that could be used to read midi, modify it , then write midi back to a file blob on the front end/browser.

just trying : 
```js
// Start with a new track
var track = new MidiWriter.Track()
track.addEvent(new MidiWriter.NoteEvent({pitch: 'C5', duration: 'T4550'}))
var track = new MidiWriter.Track();
 
// Define an instrument (optional):
track.addEvent(new MidiWriter.ProgramChangeEvent({instrument : 1}));
 
// Add some notes:
var note = new MidiWriter.NoteEvent({pitch:['C4', 'D4', 'E4'], duration: '4'});
track.addEvent(note);
 
// Generate a data URI
var write = new MidiWriter.Writer([track]);
console.log(write.dataUri());`

```
does not work as I get the error.  
 I imported in the <head> tag: 
 <script src="node_modules/midi-writer-js/build/browser/index.min.js"/>

**Comment by grimmdude** [comment]
Hi @fornof,

Try starting with this:

```js
var MidiWriter = require('MidiWriter');
```
It's a little weird I know, and could probably be improved, but that should work if using the browser build.

-Garrett

**Comment by fornof** [comment]
Oh my goodness! it works! Thank you soooo much!
