### ISSUE TITLE
Error: MidiWriter.Track() is not a constructor?

### ISSUE THREAD

**Issue by IkobaNoOkami** [grimmdude/MidiWriterJS#41]
Hi, I'm a programming rookie.
As the title say, I get this error:
<img width="700" alt="cattura" src="https://user-images.githubusercontent.com/40023626/41092459-39699de0-6a49-11e8-9ad3-dc6e7ee087a4.PNG">

<img width="797" alt="cattura2" src="https://user-images.githubusercontent.com/40023626/41092471-3ec1f5e4-6a49-11e8-9938-86cc11cdc207.PNG">

I get this error AFTER doing the npm install thing. This is the console result:
<img width="543" alt="cattura3" src="https://user-images.githubusercontent.com/40023626/41092544-6a8a74b2-6a49-11e8-93cb-bad86f62d16a.PNG">

Is it normal? I'm missing something but I don't know what.

Thank you for your help.

**Comment by benrogmans** [comment]
Check if you run the command in the right directory.

Npm cannot find the file package.json which is required for any npm project.

If you are in the right directory but you havn’t initialised your project as an NPM project yet, run:

‘npm init’

**Comment by IkobaNoOkami** [comment]
I've installed the npm in my project folder, the same warning appeared
<img width="785" alt="cattura21" src="https://user-images.githubusercontent.com/40023626/41098860-11544166-6a5d-11e8-8cd1-a4ebcc3e6029.PNG">

This is my project folder, am I missing the package.json? How I can get it?
<img width="556" alt="cattura22" src="https://user-images.githubusercontent.com/40023626/41098895-29013116-6a5d-11e8-8a14-9b4bfa9535aa.PNG">

It's one of my first time using Javascript, I'm not sure how to use the npm initializator correctly.

Thank you, for your help!

**Comment by IkobaNoOkami** [comment]
I tried to change the project folder destination, the console report the same warnings:
<img width="825" alt="cattura23" src="https://user-images.githubusercontent.com/40023626/41104213-2381c3aa-6a6b-11e8-885c-11760959f986.PNG">

But the project folder now contains some new files:
<img width="544" alt="cattura24" src="https://user-images.githubusercontent.com/40023626/41104249-33fda2da-6a6b-11e8-958e-4234074c7802.PNG">

Anyhow, the result is not changed. I'm still getting the TypeError: MidiWriter.Track is not a constructor.

**Comment by benrogmans** [comment]
Run the command:

npm init
