### ISSUE TITLE
No sound in midi file

### ISSUE THREAD

**Issue by CropFarmer** [grimmdude/MidiWriterJS#42]
Here's my code (I'm using discord.js and node.js btw, the code is supposed to make a random midi)
![image](https://user-images.githubusercontent.com/45299592/48961278-20092280-ef28-11e8-8a54-a92abb2befbc.png)
![image](https://user-images.githubusercontent.com/45299592/48961306-50e95780-ef28-11e8-8ade-7ca8680d5153.png)

no errors occur, it's just when i open the midi file, it has no sound
i did the same code with the example tracks (minus the random numbers and stuff) and the sound was fine. any fix?
Edit: There is sound, but it's really really quiet. How do i make it louder?

**Comment by grimmdude** [comment]
Hi @CropFarmer,

Thanks for your message.  I'm guessing you were able to figure out your issue since this has been closed? 

-Garrett
