### ISSUE TITLE
how to use different duration for each note in note array

### ISSUE THREAD

**Issue by drumtj** [grimmdude/MidiWriterJS#53]
hi
How to add note event with different lengths at the same time?

[MidiWriterJS]
`new MidiWriter.NoteEvent({pitch:['C4', 'D4', 'E4'], duration: '4'});`

[Tone js example]
`poly.triggerAttackRelease(["Eb3", "G4", "C5"], "2n");`
`poly.triggerAttackRelease(["Eb3", "G4", "C5"], ["2n", "4n", "4n"]);` ---> i need like this

**Comment by grimmdude** [comment]
Hi @drumtj,

Currently the best way to create concurrent note events with different durations is by using different tracks.

-Garrett

**Comment by drumtj** [comment]
Hi..

I am already using multitrack for several instruments.
Is it impossible to apply multiple notes of different lengths to a single note event?

**Comment by grimmdude** [comment]
Hi @drumtj,

Sorry, I don't believe there is currently a way to define simultaneous starting notes with different durations on a single track.  Would be a cool feature though, can take a look at it when I get a chance.

-Garrett

**Comment by grimmdude** [comment]
Hi @drumtj,

One thing I just thought of; you can try using the `Track.mergeTrack()` method to combine two tracks with different event durations into one.  It's sort of experimental currently but may work well enough.

http://grimmdude.com/MidiWriterJS/docs/Track.html#mergeTrack

-Garrett
