### ISSUE TITLE
Document MidiWriter.saveMIDI

### ISSUE THREAD

**Issue by leegee** [grimmdude/MidiWriterJS#54]
Please document `MidiWriter`'s `saveMIDI` method - I only found it through [StackOverflow](https://stackoverflow.com/questions/19192590/javascript-how-to-export-a-midi-file).

**Comment by PedroAlvesV** [comment]
Well... http://grimmdude.com/MidiWriterJS/docs/Writer.html#saveMIDI

Em seg, 29 de abr de 2019 às 07:54, Lee Goddard <notifications@github.com>
escreveu:

**Comment by leegee** [comment]
Didn't find that doc. Guess I thought the readme was exhaustive.

Thanks!

**Comment by grimmdude** [comment]
Yep you can find it documented there.  Though, I sorta feel like it's better to just handle the save logic separately since you may want to use different options, etc.  Something like this:
```js
const fs = require('fs');
const write = new MidiWriter.Writer(track);
const buffer = new Buffer(write.buildFile());
fs.writeFile('my-midi-file.mid', buffer, function (err) {
    if(err) throw err;
});
```

**Comment by leegee** [comment]
In any case, your module saved me a lot of time and allowed me to get on
with the music -- many thanks!
