### ISSUE TITLE
open to a bit of code tidying?

### ISSUE THREAD

**Issue by jpw** [grimmdude/MidiWriterJS#60]
Hi there,

I'm using MidiWriterJS for a small node project generating music via the wonder of MIDI files. Thanks very much for MidiWriterJS!

I'm interested in contributing to the codebase as and when I can, and was wondering what your feelings were on a PR adding linting to the project and doing some tidying as a first step?

**Comment by grimmdude** [comment]
Hi @jpw,

Sure!  PRs which improve the library are always welcome.  Thanks,

-Garrett

**Comment by jpw** [comment]
Cool! Please see #62 hope you like.
