### ISSUE TITLE
Merge tracks in parallel

### ISSUE THREAD

**Issue by michaelmior** [grimmdude/MidiWriterJS#63]
I have tracks for several different notes on the same instrument that I'm constructing independently. I get the current sound when I export these tracks as an array. However, I want the output to have a single track. When I use `mergeTracks`, I the tracks end up appearing one after the other. Is there any easy way to do this?

**Comment by grimmdude** [comment]
Hi @michaelmior,

Thanks for your message.  `mergeTracks` _should_ merge in parallel, but it's admittedly a bit experimental at the moment.  Could you post your code so I can test it out and possibly figure out what's going on?

-Garrett

**Comment by michaelmior** [comment]
Thanks! Here's [the function which generates each track](https://github.com/michaelmior/rhythm-wheel/blob/master/src/Wheel.js#L33)  and [the function which merges them](https://github.com/michaelmior/rhythm-wheel/blob/master/src/Player.js#L25).

**Comment by jpw** [comment]
Please excuse me for butting in :)

Hi @michaelmior I was intrigued so I had a quick look, and your app appears to export MIDI files just fine...

Have I missed something, or how can the problem be reproduced?

**Comment by michaelmior** [comment]
The app does indeed export MIDI. However, each instrument is on a separate track where I would prefer them all to be on a single track.

**Comment by xp2-882030kgz010602** [comment]
I am having the same issue too.

**Comment by grimmdude** [comment]
Hi @michaelmior, I'm not able to replicate this currently.  I've added a test for `Track.mergeTrack()` with a very basic example which is currently passing, but please let me know if you're still having trouble.

@xp2-882030kgz010602, if you could post some example code that illustrates the problem you're seeing I can take a closer look.

In the meantime, closing this one out for now.
