### ISSUE TITLE
pitch bend event

### ISSUE THREAD

**Issue by LagodViads** [grimmdude/MidiWriterJS#65]
It seems Pitch Bend was not implemented. 

The following patch implements this by adding a new class :

PitchBendEvent

Using field "bend", containing a float ranging [-1,1], zero meaning no bend.

[addPitchBendpatch.txt](https://github.com/grimmdude/MidiWriterJS/files/3505320/addPitchBendpatch.txt)

**Comment by grimmdude** [comment]
Hi @LagodViads,

Thanks very much for implementing this, I've merged it into master via PR #66.

-Garrett
