### ISSUE TITLE
impossible to add CC automations 

### ISSUE THREAD

**Issue by iBundin** [grimmdude/MidiWriterJS#68]
Hello. There are no data related to timing in Track.ControllerChange(cc#, val).  Only one CC value is exported for each track at tick position 0. I would suggest moving ControlChange to Event type and adding startTick argument to it. In case there is some mechanic to store CC automation, it would be great to add it to documentation. Thank you!

**Comment by grimmdude** [comment]
Hi @iBundin (& @rualark, @willemodendaal, @jonvandermeulen, @jeffm)

Sorry for such a late reply, finally getting around to addressing some of these.

You should be able to add controller change events at any point in a track by adding it like this:

```js
track.addEvent(new MidiWriter.ControllerChangeEvent({controllerNumber: 1, controllerValue: 127}));
```

This event will be added with a zero tick delta from the event before it.
