### ISSUE TITLE
Place EndTrackEvent at a particular tick

### ISSUE THREAD

**Issue by chr15m** [grimmdude/MidiWriterJS#84]
Thank you for MidiWriterJS, it's fantastic! I'm creating short MIDI loops with it. At the moment if my last note is somewhere in the middle of a loop, the midi track is shorter than it should be. Here's an example of a loop that falls short of the end of the bar:

![screenshot](https://user-images.githubusercontent.com/67130/132858953-813aa65a-2405-40b3-b2ab-e95f0cc272dd.png)

To mitigate this I am placing a note with `{duration: "T1", pitch: 0, velocity 0, startTick: (looplength - 1)}` which seems to work:

![screenshot](https://user-images.githubusercontent.com/67130/132859334-ff04de1d-c446-49d9-bbf2-c77d00cc2c1e.png)

It feels like a bit of a hack. I wonder if there should be a way to tell MidiWriterJS that the track should end at a particular tick?

Thanks so much for this library.

**Comment by lplume** [comment]
i was thinking a little bit about this, wouldn't fit better in MidiWriterJS a way to autofill emtpy measures? what do you think about this?
At the moment I really do not have ideas on how the api could look like, but seems a good idea to me.

thanks

**Comment by grimmdude** [comment]
Hey @chr15m thanks for your message!  I can see what you mean.

@lplume, yea auto-padding a track to the end of the measure would probably be a good default behavior.  I wonder if it would also be useful to have a`Track.length` property which could override it.  Could potentially provide more granular adjustments down to the tick.

I'll take a look shortly and see what we can do.

**Comment by lplume** [comment]
feel free to ping me again about this or other things, i'd like to code again on midiwriterjs!

**Comment by grimmdude** [comment]
@lplume awesome, feel free to tackle this one if you like!

**Comment by lplume** [comment]
a little busy lately, still thinking about this and could be tricky to "automagically" detect when to pad the track to the measure lenght if needed. @davay42 since you notice this as well, how do you think midiwriter should behave? Could you give a few examples based on your use cases in the form of "I have to do this [code example]" and how do you think it should be [code example]? That would be very useful. Also @chr15m at the moment do you experience to "hacky" the filling of the track with a 0-pitch note only at the end of it?

thanks

**Comment by chr15m** [comment]
@lplume yes padding with an empty note feels hacky. Ideally there would be a way to situate the end-track even directly at the time where the user wants it but I don't know if the MIDI format supports this. I note it is possible elsewhere in the API to situate events at specific time points though so it seems like it should be possible.

**Comment by davay42** [comment]
@lplume I think just the ability to set the end-of-track event manually at a certain time would be enough for the purpose.

**Comment by davay42** [comment]
@lplume Interestingly Garage band recognizes the loop length correctly with `midiTrack.setTempo(tempo.bpm); midiTrack.setTimeSignature(4, 4)` in place. Works even for empty loops. The calculations shouldn't be too fancy here. 

The issue arises when I try to import a midi file to my web editor back. So we need to do the calculations ourselves.

**Comment by grimmdude** [comment]
I've made some changes in #107 to allow `EndTrackEvent` to be manually added with a specific delta value.  That is, that number of ticks from the previous event.

```js
track.addEvent(new MidiWriter.EndTrackEvent({delta: 128}));
```

Might still be easier/more readable to pad a track with a silent note @chr15m, but at least this is now an option.

**Comment by chr15m** [comment]
Awesome, thank you, will check it out.

**Comment by davay42** [comment]
Awesome, thanks!
