### ISSUE TITLE
How to caculate "tick" properly?

### ISSUE THREAD

**Issue by humbleCoder1990** [grimmdude/MidiWriterJS#87]
![스크린샷 2022-01-19 오전 2 00 21](https://user-images.githubusercontent.com/87828192/149983628-7ffb497a-6f06-41ee-b5ee-56f8e1be00e9.png)

I tried to make 1 bar with 16 notes.

So, I caculated durationTick like this.

`const duration = 1920 / 16 /* 1920 ticks are 1 bar */`

then, 

`const startTick = duration * noteIndex`

But the result is almost 4 bars like the screenshot.
What are I missing something?
How to caculate ticks properly?

MidiWriterJS uses another value for meaning 1 bar of ticks?

**Comment by humbleCoder1990** [comment]
Wow I just saw another post https://github.com/grimmdude/MidiWriterJS/issues/58,
128 ticks for per beat.
It's very confusing.

**Comment by grimmdude** [comment]
Hi @humbleCoder1990,

That's correct, there are 128 ticks per beat.  That's how it's specified in MIDI 🤷‍♂️
