### ISSUE TITLE
Client side version?

### ISSUE THREAD

**Issue by wrcstewart** [grimmdude/MidiWriterJS#88]
Hi
I was wondering how tricky it would be to set up a client side .js file. I see there is 1 dependency. I believe there are programs that can process .npm files/packages to form client side version. But I am not at all knowledgable about those ...
Any thoughts ?

**Comment by grimmdude** [comment]
Hey @wrcstewart, I've just added a browser build here which exposes the global variable `MidiWriter`.  Hope that helps!

https://github.com/grimmdude/MidiWriterJS/blob/master/browser/midiwriter.js

**Comment by wrcstewart** [comment]
Thanks

**Comment by wrcstewart** [comment]
Hi
Sorry to bother you. I was wondering if it is possible to use the program change event to select a drum part - as it only seems to take a single integer? I'm a newbie with midi.Thanks
William

    On Wednesday, 9 February 2022, 06:25:05 CET, Garrett Grimm ***@***.***> wrote:  
 
 


Hey @wrcstewart, I've just added a browser build here which exposes the global variable MidiWriter. Hope that helps!

https://github.com/grimmdude/MidiWriterJS/blob/master/browser/midiwriter.js

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wrcstewart** [comment]
Hi
Cancel my last question re drums i ve found the answer.
Thanks
William
