### ISSUE TITLE
Support Key Signature

### ISSUE THREAD

**Issue by lplume** [grimmdude/MidiWriterJS#9]
This is one of the few meta events left to be implemented. I can take a walk through this the next week if you do not plan to implement it.

**Comment by lplume** [comment]
Started working on this, could you please take a look at the commit
https://github.com/lplume/MidiWriterJS/commit/589ab7dd1e28da0c06c2ea07a8fc26e563f13b8c

My question, before pull requesting, is the following: the key signature is now specified as a pair of
```javascript
track.setKeySignature(sf, mi)
```
where `sf` is the number of sharps or flats (<0 flats; 0 key of C, >0 sharps) and `mi` is the mode (0 major, 1 minor).

So for the Am signature `track.setKeySignature(0, 1)` (key of C no sharps or flats, minor), for A `track.setKeySignature(3, 0)` (three sharps, major).

Do you think is it enough? Maybe it could be useful to autodetect the number of sharps/flats based on the key:

- `track.setKeySignature('Am')`: auto-detect to `setKeySignature(0, 1)`
- `track.setKeySignature('A')`: auto-detect to `setKeySignature(3, 0)`
- `track.setKeySignature('Bbm')`: auto-detect to `setKeySignature(-5, 1)`

**Comment by grimmdude** [comment]
Hi @lplume ,

I was looking at this over the weekend as well.  I think it would make the most sense 'auto detect' like you have in your examples by accepting the key name as an argument.  It's pretty standard nomenclature to use Am, D, F#m etc so I think that should work well.

Have you found if it's possible to set multiple key signatures?

-Garrett

**Comment by lplume** [comment]
Hi @grimmdude,

since the meta event is related to the track chunk, yes it is possible (I also test differents key signature at the same tempo on different tracks).
Consider also:

1. Key signature could change during execution
2. Some instruments (see Brass) should need different key signature

**Comment by lplume** [comment]
pr #14
