### ISSUE TITLE
How to write out drum tracks

### ISSUE THREAD

**Issue by wrcstewart** [grimmdude/MidiWriterJS#91]
I'm not sure how midi files record the fact that the track is intended for channel 10. Is there a way to make the track write to ch10 in MidiWriterJS. In other words how does one write out drum parts - an example bit of code would be great.

**Comment by grimmdude** [comment]
Hey @wrcstewart,

You can define the channel per note.  Admittedly I haven't worked much with drum parts, but this should work:

```js
// Add a single note on channel 10
const note = new MidiWriter.NoteEvent({pitch: ['C4'], duration: '4', channel: 10});
track.addEvent(note);

// Add multiple notes on channel 10
track.addEvent([
    new MidiWriter.NoteEvent({pitch: ['C4'], duration: '4'}),
    new MidiWriter.NoteEvent({pitch: ['D4'], duration: '4'}),
    new MidiWriter.NoteEvent({pitch: ['E4'], duration: '4'}),
], function(event) {
    return {channel: 10};
});
```

**Comment by wrcstewart** [comment]
Fantastic 
thanks
