### ISSUE TITLE
Seems to hang on using the writer

### ISSUE THREAD

**Issue by ayunami2000** [grimmdude/MidiWriterJS#92]
![image](https://user-images.githubusercontent.com/24785136/153727021-8e978350-7845-449d-8c85-f3bbdf17fbcd.png)
![image](https://user-images.githubusercontent.com/24785136/153727030-980bb247-c497-48be-86a2-b4b168ca3f69.png)

It hangs right before the `console.log(123);` part and I can't figure out why. I have tested if it's hanging in the for loop but it goes through that in under a second.

The whole thing is run async if that means anything

**Comment by ayunami2000** [comment]
I got it to work using a different library: https://github.com/dingram/jsmidgen

But I'll keep this open so you guys can patch the issue.

**Comment by grimmdude** [comment]
Hey @ayunami2000,

Thanks for reporting!  If you could provide some reproducible code, that would help us debug this issue.

**Comment by ayunami2000** [comment]
Once I get home after school (~10 or so hours) I'll get details like my node version and some code to reproduce the issue.

**Comment by dturner34** [comment]
I was able to reproduce this by accidentally sending a messed up duration 'T-100'.

**Comment by grimmdude** [comment]
Thanks @ayunami2000 & @dturner34.

I've added some validation for this which throws an error if an invalid duration is used.  Hopefully that should shine some light on the issue you were having @ayunami2000.
