### ISSUE TITLE
Why does a slower tempo create a little rest between NoteEvents?

### ISSUE THREAD

**Issue by AndaRebeca** [grimmdude/MidiWriterJS#99]
I have a track with 4 chords having:
time signature: (4/4)
bpm (tempo): 120
duration of the NoteEvent : "T512"

When I change the bpm to 60, a little rest appears between chords. How can I make the chords play cursively as when I have a bpm of 120?
@grimmdude

**Comment by marian-simonca** [comment]
This is happening to us as well for the same configuration.
Any help? @grimmdude

**Comment by grimmdude** [comment]
Hi @AndaRebeca & @marian-simonca, I can't seem to replicate this issue.  When I create a MIDI file using those parameters I end up with each chord being held for a whole note as I would expect, given that each beat consists of 128 ticks.

Here's the code I'm using, can you post your code?

```js
const MidiWriter = require('midi-writer-js');

const track = new MidiWriter.Track();

track.setTempo(60);
track.setTimeSignature(4, 4);

track.addEvent([
	new MidiWriter.NoteEvent({pitch: ['C4', 'E4','G4'], duration: 'T512'}),
	new MidiWriter.NoteEvent({pitch: ['C4', 'E4','G4'], duration: 'T512'}),
	new MidiWriter.NoteEvent({pitch: ['C4', 'E4','G4'], duration: 'T512'}),
	new MidiWriter.NoteEvent({pitch: ['C4', 'E4','G4'], duration: 'T512'}),
]);

const write = new MidiWriter.Writer(track);
console.log(write.dataUri());

```
